@FraudSys_HostAddress = https://localhost:7000
# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST {{FraudSys_HostAddress}}/Cliente/CriaCliente
Content-Type:application/json
{
    "CPF":"484.312.518-08",
    "NumeroAgencia":"12345678",
    "NumeroConta":"9101112",
    "LimitePIX":100
}
###
POST {{FraudSys_HostAddress}}/Cliente/CriaCliente
Content-Type:application/json
{
    "CPF":"484.312.518-08",
    "NumeroAgencia":"12345679",
    "NumeroConta":"9101112",
    "LimitePIX":100
}
###
POST {{FraudSys_HostAddress}}/Cliente/CriaCliente
Content-Type:application/json
{
    "CPF":"123.456.789-18",
    "NumeroAgencia":"12345670",
    "NumeroConta":"9101112",
    "LimitePIX":100
}
###
POST {{FraudSys_HostAddress}}/Cliente/CriaCliente
Content-Type:application/json
{
    "CPF":"213.645.987-08",
    "NumeroAgencia":"12345677",
    "NumeroConta":"9101112",
    "LimitePIX":100
}
###
DELETE {{FraudSys_HostAddress}}/Cliente/DeletaCliente/12345678/9101112
Content-Type:application/json
###
POST {{FraudSys_HostAddress}}/Cliente/AtualizaLimite
Content-Type:application/json
{
    "NumeroAgencia":"12345678",
    "NumeroConta":"9101112",
    "NovoLimite":200
}
###
GET {{FraudSys_HostAddress}}/Cliente/BuscaCliente/12345678/9101112
Content-Type:application/json
###
POST {{FraudSys_HostAddress}}/Transacao
Content-Type:application/json
{
    "NumeroAgenciaOrigem" :"12345678",
    "NumeroContaOrigem":"9101112",
    "NumeroAgenciaDestino":"12345678",
    "NumeroContaDestino":"9101112",
    "ValorTransacao":100
}